profilim_XPATH="//*[@id='__next']/div/nav/div[1]/ul/li[2]/a"
degerlendirmeBtn_XPATH="//*[@id='__next']/div/nav/div[1]/ul/li[3]/a"
katalogBtn_XPATH="//*[@id='__next']/div/nav/div[1]/ul/li[4]/a"
takvimBtn_XPATH="//*[@id='__next']/div/nav/div[1]/ul/li[5]/a"
anasayfaBtn_XPATH="//*[@id='__next']/div/nav/div[1]/ul/li[1]/a"
egitimlerimBtn_ID="lessons-tab"
duyuruHaberlerimBtn_ID="notification-tab"
anketlerimBtn_ID="mySurvey-tab"
basvurularimBtn_ID="apply-tab"
sinavlarimBtn_XPATH="//*[@id='__next']/div/main/div[1]/section[3]/div/div/div[2]/div"
logoutButton_CSS_SELECTOR="body > div.fade.modal.show > div > div > div > div > div.d-flex.justify-content-between.mb-8 > button"
profiliOlusturBtn_XPATH="//*[@id='__next']/div/main/div[1]/section[4]/div/div/div[1]/div/button"
kendiniDegerlendirBtn_XPATH="//*[@id='__next']/div/main/div[1]/section[4]/div/div/div[2]/div/button"
ogrenmeyeBaslaBtn_XPATH="//*[@id='__next']/div/main/div[1]/section[4]/div/div/div[3]/div/button"

