oldPassword_NAME="currentPassword"
newPassword_NAME="password"
newPasswordAgain_NAME="passwordConfirmation"
profiliOlusturBtn_XPATH="//*[@id='__next']/div/main/div[1]/section[4]/div/div/div[1]/div/button"
settingBtn_XPATH="//*[@id='__next']/div/main/section/div/div/div[1]/div/a[8]/span[2]"