giris_URL="https://tobeto.com/giris"
successPopupMessage_CSS=".btn-close:nth-child(3)"
evaluationButton_xpath="(//li[@class='nav-item'])[3]"
expectedTobetoTitle="Tobeto İşte Başarı Modeli"
tobetoTitleText_CSS=".dashboard-card > span"
startButton_CSS=".btn.btn-primary"
isteBasariModeli_link1="https://tobeto.com/profilim/degerlendirmeler/tobeto-iste-basari-modeli"
startEvaluationButton_CSS=".btn.btn-primary.d-inline-block.mt-8"
isteBasariModeli_link2="https://tobeto.com/profilim/degerlendirmeler/tobeto-iste-basari-modeli/1"
#format yöntemiyle araya for döngüsüyle 1 den 10 kadar yazdırmak için locate böyle aldık.
questionAnswers_xpath="(//div[@id='__next']/div/main/section/div/div/div[2]/div/table/tbody/tr/td[6]/input)[{}]"
forwardButton_xpath="//button[@class='btn btn-primary d-inline-block'][contains(text(),'İleri')]"
finishButton_xpath="//a[@class='btn btn-primary d-inline-block'][contains(text(),'Değerlendirmeyi Bitir')]"
showReport_CSS=".btn.btn-primary"
expectedMyAnalysisReport="Analiz Raporum"
actualMyAnalysisReport_CSS=".h6.text-center"
yedekEmail="wecev42059@buzblox.com"
expectedMyAnalysisReportLink="https://tobeto.com/profilim/degerlendirmeler/rapor/tobeto-iste-basari-modeli/1"
frontEndStartButton_xpath="//button[@class='btn btn-light']"
actualExamName_CSS=".quiz-details-header"
expectedExamName="Front End"
startExamButton_CSS=".btn.btn-primary.mt-8.ms-auto.me-auto"
closeExamButton_CSS=".btn.btn-primary.mt-8.ms-auto.me-auto"
firstOption_xpath="//div[@class='option ']"
forwardQuestionButton_xpath="//button[@class='btn btn-next']"
frontEndShowReportButton_xpath="//button[@class='btn btn-light']"
showReportButton_CSS=".btn.btn-primary.mt-8.ms-auto.me-auto"
closeReportButton_CSS=".btn.btn-primary.mt-8.ms-auto.me-auto"
