giris_URL="https://tobeto.com/giris"
successPopupMessage_CSS=".btn-close:nth-child(3)"
profilDropdownMenu_CSS=".name"
profileInformationButton_xpath="//a[@class='dropdown-item profil-dropdown']"
myEducationLifeButton_xpath="//span[contains(text(),'Eğitim Hayatım')]"
educationStatusButton_CSS="[name='EducationStatus']"
educationChoice_CSS="[value='Lisans']"
universityInputBox_xpath="//input[@name='University']"
universityInfo="Marmara Üniversitesi"
departmentInputBox_xpath="//input[@name='Department']"
departmentInfo="Matematik"
startDate_xpath="//input[@placeholder='Başlangıç Yılınızı Seçiniz']"
startDate="2012"
startDateFromCalendar_xpath="//div[@class='react-datepicker__year-text' and contains(text(), '2017')]"
finishDate_xpath="//input[@placeholder='Mezuniyet Yılınızı Seçiniz']"
finishDate="2018"
finishDateFromCalendar_xpath="//div[@class='react-datepicker__year-text' and contains(text(), '2022')]"
saveButton_xpath="//button[contains(text(),'Kaydet')]"
successPopUpMessage_CSS=".toast-body"
successPopUpMessage_xpath="//div[@class='toast-body']"
successPopUpMessage="• Eğitim bilgisi eklendi."
educationVerify_CSS=".my-grade:nth-child(1) .grade-details-col:nth-child(1) > .grade-details-content"
educationVerify_xpath="(//span[contains(text(),'Üniversite')])[1]/following-sibling::span"
continueEducationButton_CCS=".d-flex.mt-3.text-start > input"
continueEducationVerify_CSS=".grade-header > span"
continueEducationTitle="Devam Ediyor"
errorMessages_CSS=".text-danger"
errorMessage="Doldurulması zorunlu alan*"
deleteButton_CSS=".grade-delete.g-del"
deleteButton_xpath="(//span[@class=' grade-delete g-del'])[1]"
popUpMessage_CSS=".alert-message.mx-3"
popUpMessage="Seçilen eğitimi silmek istediğinize emin misiniz?"
noButton_CSS=".btn.btn-no.my-3"
yesButton_CSS=".btn.btn-yes.my-3"
successDeleteEducationPopUpMessage_CSS=".toast-body"
successDeleteEducationPopUpText="Eğitim kaldırıldı."
max_characterControl_text="Marmara Üniversitesi, İstanbul'un Anadolu yakasında, Üsküdar ilçesinde bulunan ve Türkiye'nin önde gelen yükseköğretim kurumlarından birisidir. Köklü geçmişi, geniş kampüsü ve nitelikli akademik kadrosuyla öne çıkan üniversite, eğitimde kaliteyi ve öğrenci memnuniyetini ön planda tutmaktadır. Araştırma, eğitim ve toplumsal hizmet alanlarında başarılı çalışmalar yapan Marmara Üniversitesi, ulusal ve uluslararası alanda tanınmaktadır."
maxCharErrorMessage="En fazla 50 karakter girebilirsiniz"
min_characterControl_text="x"
minCharErrorMessage="En az 2 karakter girmelisiniz"



