baseUrl = "https://tobeto.com/giris"
emailInputXpath = "(//*[@class='form-control mt-6'])[1]"
passwordInputXpath = "(//*[@class='form-control mt-6'])[2]"
validEmail = "ahmetsuattanis2@gmail.com"
validPassword = "Ahmet9876543210"
girisYapButtonCss = ".btn:nth-child(3)"
profilimButtonCss = ".nav-link.c-gray-3"
profilDuzenleCss = ".cv-edit-icon"
yabanciDillerimButtonCss = ".btn:nth-child(7) > .sidebar-text"
languageButtonName = "languageName"
dropdownLanguageXpath = "//*[@id='__next']/div/main/section/div/div/div[2]/form/div/div[1]/select"
dropdownEnglishXpath = "//*[@id='__next']/div/main/section/div/div/div[2]/form/div/div[1]/select/option[12]"
proficiencyButtonName = "proficiency"
languageLevelXpath = "//option[. = 'Orta Seviye (B1 , B2)']"
saveButtonCss = "form > .btn.btn-primary.d-inline-block.mb-3.mobil-btn.py-2"
popupMessageCss = ".toast-body"
saveSuccesText = "• Yabancı dil bilgisi eklendi."
blankLanguageChooseText = "Doldurulması zorunlu alan*"
blankLanguageChooseXpath = "//*[@id='__next']/div/main/section/div/div/div[2]/form/div/div[1]/p"
blankProficiencyXpath = "//*[@id='__next']/div/main/section/div/div/div[2]/form/div/div[2]/p"
blankProficiencyText = "Doldurulması zorunlu alan*"
succesAddedEnglishXpath = "//*[@id='__next']/div/main/section/div/div/div[2]/div/div/div"
deleteEnglishLanguageCss = ".delete-lang"
alertMessage1Xpath= "//*[@Class='alert-message mx-3']"
alertMessage1Text = "Seçilen yabancı dili silmek istediğinize emin misiniz?"
alertMessage1Xpath= "//*[@Class='alert-message-light mx-3']"
alertMessage1Text = "Bu işlem geri alınamaz."
allertBtnEvet = ".btn.btn-yes.my-3"
allertBtnHayirCss = ".btn.btn-no.my-3"
popupDeleteMessageText = "• Yabancı dil kaldırıldı." 