BASE_URL="https://www.saucedemo.com/"
username_id="user-name"
password_id="password"
username="standard_user"
password="secret_sauce"
login_button_id="login-button"
errorMessage_xpath="//*[@id='login_button_container']/div/form/div[3]/h3"
errorMessage1_text="Epic sadface: Username is required"
errorMessage2_text="Epic sadface: Password is required"
errorMessage3_text= "Epic sadface: Sorry, this user has been locked out."
baslik_xpath= "//div[@class='app_logo']"
baslik_text="Swag Labs"
listOfProducts_CSS="div[class='inventory_item']"
listOfProducts_length=6
errorMessage4_text = "Epic sadface: Username and password do not match any user in this service"
item1_name="add-to-cart-sauce-labs-bike-light"
item2_name="add-to-cart-sauce-labs-bike-light"
item3_CSS="#add-to-cart-sauce-labs-backpack"
cartButton_CSS=".shopping_cart_badge"
cartButton_xpath="//span[@class='shopping_cart_badge']"
removeButton_CSS="#remove-sauce-labs-bike-light"
item4_name="add-to-cart-sauce-labs-bike-light"
item5_CSS="#add-to-cart-sauce-labs-backpack"
checkoutButton_id="checkout"
firstName_id= "first-name"
lastName_id="last-name"
zipCode_id="postal-code"
continueButton_id="continue"
finishButton_id= "finish"
orderConfirmMessage_xpath="//h2[@class='complete-header']"
orderConfirmMessage_text="Thank you for your order!"