login_URL="https://tobeto.com/giris"
userEmail="ahmetsuattanis2@gmail.com"
userPassword="Ahmet9876543210"
email_CSS="[name='email']"
password_CSS="[name='password']"
loginButton_CSS=".btn.btn-primary.w-100.mt-6"
successLogin_CSS=".toast-body"
successLogin_message="• Giriş başarılı."
emailErrorMessage_CSS="form > p:nth-of-type(1)"
emailError_Message="Doldurulması zorunlu alan*"
passwordErrorMessage_CSS="form > p:nth-of-type(2)"
passwordError_Message="Doldurulması zorunlu alan*"
invalidEmailOrPassword_errorMessage="• Geçersiz e-posta veya şifre."
invalidEmailOrPassword_errorMessage_CSS=".toast-body"
deactiveUserEmail="ahmetsuattanis91@gmail.com"
deactiveUserPassword="123456.=."
deactiveUserLogin_errorMessage = "• Henüz e-posta adresinizi doğrulamadınız."
deactiveUserLogin_errorMessage_CSS=".toast-body"
