baseUrl = "https://tobeto.com/giris"
emailInputXpath = "(//*[@class='form-control mt-6'])[1]"
passwordInputXpath = "(//*[@class='form-control mt-6'])[2]"
validEmail = "ahmetsuattanis2@gmail.com"
validPassword = "Ahmet9876543210"
girisYapButtonCss = ".btn:nth-child(3)"

profilimButtonCss = ".nav-link.c-gray-3"
profilDuzenleCss = ".cv-edit-icon"
medyaHesaplarimButtonCss = ".btn:nth-child(6) > .sidebar-text"
socialMediaButtonName = "socialMedia"
dropdownButtonName =  "socialMedia"
dropdownLinkedinXpath = "//option[. = 'LinkedIn']"
dropdownGithubXpath = "//option[. = 'Github']"
dropdownTwitterXpath = "//option[. = 'Twitter']" 
socialMediaUrlName =  "socialMediaUrl"
linkedinUrlLink = "https://www.linkedin.com/in/ahmetsuattanis"
linkedinAddedUrlCss = ".form-control.input-linkedin"
attribute = "value"
kaydetButtonCss = ".btn-primary"
maxAccountMessageXpath = "//*[@id='__next']/div/main/section/div/div/div[2]/span"
maxAccountMessageText = "En fazla 3 adet medya seçimi yapılabilir."
popupMessage = ".toast-body"
succesAccountAddedMessageText = "• Sosyal medya adresiniz başarıyla eklendi."
succesAccountDeleteMessageText = "• Sosyal medya adresiniz başarıyla kaldırıldı."
gitHubUrlLink = "https://github.com/AhmetSuatTanis"
githubAddedUrlCss = ".form-control.input-github"
twitterUrlLink = "https://twitter.com/youngold101"
twitterAddedUrlCss = ".form-control.input-twitter"

blankBoxClasName = "text-danger"
blankBoxText = "Doldurulması zorunlu alan*"

deleteBtnCss = ".btn.social-delete"
allertMessage1Xpath = "//*[@class='alert-message mx-3']"
allertMessage1Text = "Seçilen sosyal medya hesabını silmek istediğinize emin misiniz?"

allertMessage2Xpath = "//*[@class='alert-message-light mx-3']"
allertMessage2Text = "Bu işlem geri alınamaz."

popupCloseButtonXpath = "//*[@id='exw-launcher-frame-body']/div/div/div/div[1]/div[2]/button/svg"
succesAddedLinkedinXpath = "//*[@id='__next']/div/main/section/div/div/div[2]/div[2]/div"
allertBtnEvet = ".btn.btn-yes.my-3"
allertBtnHayirCss = ".btn.btn-no.my-3"

editBtnCss = ".fa.fa-pencil-square"

updateHeaderCss = ".modal-body"
updateHeaderText = "Medya Hesabı Güncelleme"
newSocialMediaButtonXpath = "(//*[@class='form-select'])[2]"
newSocialMediaUrlXpat = "(//*[@class='form-control'])[2]"
updateButtonXpath = "(//*[@type='button'])[4]"
updateButtonActiveXpath = "(//*[@class='btn btn-primary'])[1]"
kapatButtonXpath = "/html/body/div[3]/div/div/div[2]/button[2]"
succesUpdateAccauntPopupText = "Sosyal medya hesabınız başarıyla güncellendi"
newDropDownButtonXpath = "(//*[@class='form-select'])[2]"
newDropDownGithubXpath = "(//option[. = 'Github'])[2]"



