baseUrl = "https://tobeto.com/giris"
sifremiUnuttumCss=".d-block"
ePostaXPath = "//*[@id='__next']/div/main/section/div/div/div/input"
gonderCss = ".btn.btn-primary.mt-6.w-100"
gecersizformatmail = "xxx"
gecersizformattext = "• Girdiğiniz e-posta geçersizdir."
yeniSifreXpath = "/html/body/div[1]/div/main/section/div/form/div/div/input[1]"
sifreTekrarXpath = "/html/body/div[1]/div/main/section/div/form/div/div/input[2]"
sifreGonderCss = ".bg-white.px-12.py-12.shadow-lg.text-center"
sifreEslesmediText = "• Şifreler Eşleşmedi"
passwordCSS = "input[name='Passwd']"
validPassword = "235813Q!z"
validemail = "eminecskn314@gmail.com"
yeniSifreBelirleme = "123456az"
uyumsuzSifre = "123qw"
unregisteredMail = "qweas@gmail.com"
popupCss = ".toast-body"
sifreSifirlamaBasariliText = "• Şifre sıfırlama işlemi başarılı."
alertXpath = "//*[@class='toast-body']"
yeniSifreEskisifreAyni = "• Yeni şifreniz mevcut şifrenizden farklı olmalıdır."
fiveDigitPasswords = "12345"
gmailUrl = "https://mail.google.com/mail/u/0/#inbox"
fakeMailUrl="https://temp-mail.org/en/"
afterXpath = "//div[@id='identifierNext']/div/button/span"
nowLoginCss = ".VfPpkd-LgbsSe-OWXEXe-k8QpJ > .VfPpkd-vQzf8d"
inboxFirstXpath = "(//*[@jscontroller='ZdOxDb'])[1]"
firstMessageXpath = "//*[@rel='noopener']"
