baseUrl = "https://tobeto.com/giris"
emailInputXpath = "(//*[@class='form-control mt-6'])[1]"
passwordInputXpath = "(//*[@class='form-control mt-6'])[2]"
validEmail = "ecoskun3334@gmail.com"
validPassword = "123456Ec."
loginButtonCss = ".btn:nth-child(3)"

profileButtonCss = "li:nth-of-type(2) > .c-gray-3.nav-link"
lastnamefirstnameXpath = "//*[@id='__next']/div/main/div/div[2]/div[1]/div/div[1]/div/div[2]/div[1]/div[2]/span[2]"
birthDateXpath = "(//span[@class='text'])[2]"
emailXpath = "(//span[@class='text'])[3]"
phoneNumberXpath = "(//*[@class='text'])[4]"
lastnamefirstnameText = "Emine Çoşkun"
birthDateText = "25.07.1991"
emailText = "ecoskun3334@gmail.com"
phoneNumberText = "+905307953357"
aboutMeHeaderXpath= "(//div[@class='cv-box-header'])[1]"
aboutMeHeaderText = "Hakkımda"
aboutMeTextID = "user_desc"
underHeaderAboutMeXpath = "//following-sibling::p[@class='cv-desc']"
aboutMeText  = "Marmara üni Matematik bölümü mezunuyum. Kodlama , Data Science ve Yapay Zeka alanına ilgiliyim. Üniverstede temellerini attığım yazılım alanında kendimi geliştirmek istiyorum."
competencyHeaderCss = ".col-md-4 .col-12:nth-child(3) .cv-box-header span:nth-child(1)"
competencyHeaderText = "Yetkinliklerim"
competencyCText = "iletişim"

competencyCXpath = "(//following-sibling::span[@class='skill'])[1]"
seeIconCompetencyXpath = "(//*[@class='cv-see-icon'])[1]"
allCompetencyHeaderXpath = "//span[@class='grade-details-header']"
allCompetencyHeaderText = "Tüm Yetkinliklerim"
btnClaoseAllCompetencyCss = ".modal-header > .btn-close"

foreingLanguagesHeaderCss = ".col-12:nth-child(4) .cv-box-header > .d-flex > span"
foreingLanguagesHeaderText = "Yabancı Dillerim"
foreingLanguagesNameXpath = "//span[@class='lang-name']"
foreingLanguagesDegreeXpath = "//span[@class='lang-degree']"
foreingLanguagesNameText = "İngilizce"
foreingLanguagesDegreeText = "Temel Seviye ( A1 , A2)"
certificateHeaderCss = ".col-12:nth-child(5) .cv-box-header > span"
certificateHeaderText = "Sertifikalarım"
pngIconXpath = "//*[@id='certificate_name']/span[2]"
mediaAccountHeaderCss = ".col-12:nth-child(6) span"
mediaAccountHeaderText = "Medya Hesaplarım"
LinkedinIconClass = "cv-linkedin"
expectedLinkedinUrl = "https://tobeto.com/profilim" 
analysisReportItem1 = "5 Profesyonel duruşumu geliştiriyorum"

assesmentTestXpath = "//*[@class='label']"
professionalAttitudeXpath = "(//*[@class='legendName'])[2]"
seeIconAnalysisReportXpath = "(//*[@class='cv-see-icon'])[2]"
analysisReportTextClassName = "h6.text-center"
levelTestsXpath = "//*[@class=' envantory-result']"
levelTestItem1 = "Herkes İçin Kodlama 4A Değerlendirme Sınavı, 25-12-2023, 76.00"
profileButton2Css = "li:nth-of-type(2) > .c-gray-3.nav-link"

profileShare = "//*[@id='dropdown-basic']"
badgesimgClassName = "img-fluid"
tagnameImg = "img"
oldAktivity = "06/11/2023 :  1 adet aktivite"
weeksClassName = "react-calendar-heatmap-week"
allWeeksTagname = "rect"
colorPaleteClassName = "hm-colors"
colorSamplesClassName = "span"

