giris_URL="https://tobeto.com/giris"
successPopupMessage_CSS=".btn-close:nth-child(3)"
profilDropdownMenu_CSS=".name"
profilBilgileriButonu_xpath="//a[@class='dropdown-item profil-dropdown']"
sertifikalarimButonu_xpath="(//span[@class='sidebar-text'])[5]"
dosyaYuklemeButonu_CSS=".cursor-pointer"
gozatButonu_CSS=".uppy-u-reset.uppy-c-btn.uppy-Dashboard-browse"
iptalButonu_CSS=".uppy-DashboardContent-back"
uyariMesajiText="Sadece image/jpeg, image/png, application/pdf yükleyebilirsiniz"
gozatButonu_xpath="//input[@class='uppy-Dashboard-input']"
uyariMesajiText_CSS=".uppy-Informer-animated > p"
yukleButonu_xpath="//button[contains(text(), '1 dosyayı yükle')]"
indirButonu_xpath="(//span[@class=' fileIcon'])[1]"
silmeButonu_xpath="(//span[@class=' trashIcon'])[1]"
hayirButonu_xpath="//button[@class='btn btn-no my-3 ']"
evetButonu_xpath="//button[@class='btn btn-yes my-3']"
beklenenBasariliSilmePopUpMesaji="Dosya kaldırma işlemi başarılı."
basariliSilmePopUpMesaji_xpath="//div[@class='toast-body']"



