giris_URL="https://tobeto.com/giris"
successPopupMessage_CSS=".btn-close:nth-child(3)"
profilDropdownMenu_CSS=".name"
profilBilgileriButton_xpath="//a[@class='dropdown-item profil-dropdown']"
yetkinliklerimButonu_xpath="(//span[@class='sidebar-text'])[4]"
kaydetButonu_CSS=".btn.btn-primary.py-2.mb-3.d-inline-block.mobil-btn"
yetkinlikSecmeButonu_CSS=".css-1xc3v61-indicatorContainer"
secilenYetkinlik_CSS="#react-select-2-option-" #burda sonda 0 vardı ilk yetkinlğin locati fakat onu silerek hangi sıradaki yetkinliği eklemek istersen sırasını ekleyerek onu ekleme imkanı buldum.
yetenekEklendi_popUp_mesaji="Yetenek eklendi."
yetenekEklendiMesaji_CSS=".toast-body"
kapatmaButonu_CSS=".me-auto.mx-1 + button"
eklenenYetkinlikler_CSS=".grade-details-content"
silmeButonu_CSS=".grade-delete.g-del"
hayirButonu_CSS=".btn.btn-no.my-3"
evetButonu_CSS=".btn.btn-yes.my-3"
hataMesaji_CSS=".toast-body"
hataMesaji_text="Herhangi bir yetenek seçmediniz!"