giris_URL="https://tobeto.com/giris"
successPopupMessage_CSS=".btn-close:nth-child(3)"
profilDropdownMenu_CSS=".name"
profileInformationButton_xpath="//a[@class='dropdown-item profil-dropdown']"
myCompetenciesButton_xpath="(//span[@class='sidebar-text'])[4]"
saveButton_CSS=".btn.btn-primary.py-2.mb-3.d-inline-block.mobil-btn"
expectedSuccessfulPopUpMessage="Yetenek eklendi."
successfulPopUpMessage_xpath="//div[@class='toast-body']"
competencySelectButton_CSS=".css-1xc3v61-indicatorContainer"
competenceSelection1_CSS="#react-select-2-option-" #burda sonda 0 vardı ilk yetkinlğin locati fakat onu silerek hangi sıradaki yetkinliği eklemek istersen sırasını ekleyerek onu ekleme imkanı buldum.
expectedSuccessfulDeletePopUpMessage="Yetenek kaldırıldı."
successfulDeletePopUpMessage_CSS=".toast-body"
addedCompetencies_CSS=".grade-details-content"
deleteButton_CSS=".grade-delete.g-del"
noButton_CSS=".btn.btn-no.my-3"
yesButton_CSS=".btn.btn-yes.my-3"
succesful_CSS=".toast-body"
errorMessage_CSS=".toast-body"
expectedErrorMessage="Herhangi bir yetenek seçmediniz!"
addedCompetency_xpath="(//span[@class='grade-details-content'])[last()]"
